#include <sys/ptrace.h>
#include <sys/user.h>
#include <sys/wait.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>

/**
 * main - Entry point for strace_0
 * @argc: Argument count
 * @argv: Argument vector
 *
 * Return: 0 on success, 1 on failure
 */
int main(int argc, char *argv[])
{
    pid_t child;
    int status;
    struct user_regs_struct regs;
    int is_entry = 0; /* Next stop after initial execve will be a syscall exit */

    if (argc < 2)
    {
        fprintf(stderr, "Usage: %s command [args...]\n", argv[0]);
        return (1);
    }

    /* Completely turn off stdout buffering globally */
    setvbuf(stdout, NULL, _IONBF, 0);

    child = fork();
    if (child < 0)
    {
        perror("fork");
        return (1);
    }

    if (child == 0)
    {
        /* Child Process */
        ptrace(PTRACE_TRACEME, 0, NULL, NULL);
        /* execve will naturally raise a SIGTRAP to the parent tracer */
        execve(argv[1], argv + 1, NULL);
        perror("execve");
        exit(1);
    }
    else
    {
        /* Parent Process */
        /* Catch the initial trap generated by execve */
        waitpid(child, &status, 0);

        if (WIFEXITED(status) || WIFSIGNALED(status))
            return (0);

        /* Print the initial execve syscall number (59) */
        ptrace(PTRACE_GETREGS, child, NULL, &regs);
        printf("%llu\n", regs.orig_rax);

        /* Loop through all subsequent system calls */
        while (1)
        {
            ptrace(PTRACE_SYSCALL, child, NULL, NULL);
            waitpid(child, &status, 0);

            if (WIFEXITED(status) || WIFSIGNALED(status))
                break;

            if (is_entry)
            {
                if (ptrace(PTRACE_GETREGS, child, NULL, &regs) == 0)
                {
                    printf("%llu\n", regs.orig_rax);
                }
                is_entry = 0;
            }
            else
            {
                is_entry = 1;
            }
        }
    }

    return (0);
}
